### ISSUE TITLE
a issue

### ISSUE THREAD

**Issue by abinayaasri** [learn-co-curriculum/html-syntax-overview#7]
pdf is not opening

**Comment by maxwellbenton** [comment]
Hi @abinayaasri,

Thank you for opening this issue. Unfortunately, I was unable to confirm what this issue is in regard to. There are no PDF files currently listed in this lesson. Since all the links in this lesson are currently working, I am going to go ahead and close this issue. However, if you feel there is still an issue in this lesson, please feel free to reopen this ticket with additional information regarding the broken PDF and I would be happy to take another look.
